// Post user normal
# POST http://localhost:3000/api/users HTTP/1.1 
# content-type: application/json

# {
#     "nombre": "José Pablo",
#     "apellido": "Vázquez",
#     "correo": "jose.vazquez@iteso.mx",
#     "password": "Hola123",
#     "fecha": "05/18/2002",
#     "categorias": ["hogar", "ropa", "arte"],
#     "tipo": "user"
# }

// Post marca
# POST http://localhost:3000/api/users HTTP/1.1 
# content-type: application/json

# {
#     "nombre": "Boca",
#     "apellido": "Dragon",
#     "correo": "boca.dragon@brand.mx",
#     "password": "bocgon3000",
#     "fecha": "07/19/2015",
#     "tipo": "marca",
#     "marca": "BOCA DRAGÓN",
#     "logo": "images/logo_r2.jpg",
#     "categoria": "ropa",
#     "url": "https://www.instagram.com/bocadragon_/?hl=es"
# }

// Post bazar
# POST http://localhost:3000/api/users HTTP/1.1 
# content-type: application/json

# {
#     "nombre": "Bazar",
#     "apellido": "La Barca",
#     "correo": "bazar.la.barca@bazar.mx",
#     "password": "barzar45",
#     "fecha": "09/24/2021",
#     "tipo": "bazar",
#     "bazar": "Bazar la barca",
#     "logo": "images/logo_b1.jpg",
#     "url": "https://www.instagram.com/bazar_labarca/"
# }

// Post producto
# POST http://localhost:3000/api/products/boca.dragon@brand.mx HTTP/1.1 
# content-type: application/json

# {
#     "nombre": "Traje Vintage color Rosa",
#     "precio": 900,
#     "categoria": "ropa",
#     "stock": 15,
#     "descripcion": "All pinked-out, head-to-toe in Boca Dragon vintage heirlooms. Silk Chinese jacket, 80’s button-up, and 80’s balloon pants POW 💕💕",
#     "imagen": "images/r2_p1.jpg"
# }

// get usuario por correo
# GET http://localhost:3000/api/users/jose.vazquez@iteso.mx

//get todos los productos
# GET http://localhost:3000/api/products

// get token user by login
# GET http://localhost:3000/api/login HTTP/1.1 
# content-type: application/json

# {
#     "correo": "jose.vazquez@iteso.mx",
#     "password": "Hola123"
# }

// get token brand
# GET http://localhost:3000/api/login HTTP/1.1 
# content-type: application/json

# {
#     "correo": "boca.dragon@brand.mx",
#     "password": "bocgon3000"
# }

// get token bazaar
# GET http://localhost:3000/api/login HTTP/1.1 
# content-type: application/json

# {
#     "correo": "bazar.la.barca@bazar.mx",
#     "password": "barzar45"
# }

// get producto marca categoria
# GET http://localhost:3000/api/products HTTP/1.1 
# content-type: application/json

# {
#     "marca": "BOCA DRAGÓN",
#     "categoria": "ropa"
# }

// get user id
# GET http://localhost:3000/api/user/qwertyuiop-637a5abde3f6f33d7a14317f-user

// get marca id
# GET http://localhost:3000/api/user/qwertyuiop-637a5de5e7da54eb665cf563-marca

// get bazar id
# GET http://localhost:3000/api/user/qwertyuiop-637a5dffe7da54eb665cf566-bazar

# DELETE http://localhost:3000/api/users HTTP/1.1 
# content-type: application/json

# {
#     "id": "6369174169c9b9409eaf91ab"
# }